import '../models/product.dart';

// Sample Data for demonstration
class DummyData {
  static List<Product> getProducts() {
    return [
      Product(
        id: '1',
        name: 'Fresh Tomatoes',
        description: 'Farm-fresh organic tomatoes, rich in flavor',
        category: 'Vegetables',
        farmerPrice: 30.0,
        marketPrice: 45.0,
        imageUrl: '🍅',
        farmerId: 'F1',
        farmerName: 'Ramesh Kumar',
        unit: 'kg',
        stockQuantity: 500,
        listedDate: DateTime.now().subtract(const Duration(days: 2)),
      ),
      Product(
        id: '2',
        name: 'Sweet Mangoes',
        description: 'Alphonso mangoes, perfectly ripened',
        category: 'Fruits',
        farmerPrice: 120.0,
        marketPrice: 180.0,
        imageUrl: '🥭',
        farmerId: 'F2',
        farmerName: 'Suresh Patil',
        unit: 'kg',
        stockQuantity: 200,
        listedDate: DateTime.now().subtract(const Duration(days: 1)),
      ),
      Product(
        id: '3',
        name: 'Basmati Rice',
        description: 'Premium quality basmati rice',
        category: 'Grains',
        farmerPrice: 80.0,
        marketPrice: 120.0,
        imageUrl: '🌾',
        farmerId: 'F1',
        farmerName: 'Ramesh Kumar',
        unit: 'kg',
        stockQuantity: 1000,
        listedDate: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: '4',
        name: 'Fresh Spinach',
        description: 'Organic spinach leaves',
        category: 'Vegetables',
        farmerPrice: 20.0,
        marketPrice: 35.0,
        imageUrl: '🥬',
        farmerId: 'F3',
        farmerName: 'Vijay Singh',
        unit: 'kg',
        stockQuantity: 100,
        listedDate: DateTime.now(),
      ),
      Product(
        id: '5',
        name: 'Farm Eggs',
        description: 'Free-range chicken eggs',
        category: 'Other',
        farmerPrice: 60.0,
        marketPrice: 80.0,
        imageUrl: '🥚',
        farmerId: 'F4',
        farmerName: 'Lakshmi Devi',
        unit: 'dozen',
        stockQuantity: 150,
        listedDate: DateTime.now(),
      ),
      Product(
        id: '6',
        name: 'Green Apples',
        description: 'Crisp and juicy green apples',
        category: 'Fruits',
        farmerPrice: 90.0,
        marketPrice: 130.0,
        imageUrl: '🍏',
        farmerId: 'F2',
        farmerName: 'Suresh Patil',
        unit: 'kg',
        stockQuantity: 300,
        listedDate: DateTime.now().subtract(const Duration(days: 3)),
      ),
      Product(
        id: '7',
        name: 'Potatoes',
        description: 'Fresh farm potatoes',
        category: 'Vegetables',
        farmerPrice: 25.0,
        marketPrice: 40.0,
        imageUrl: '🥔',
        farmerId: 'F3',
        farmerName: 'Vijay Singh',
        unit: 'kg',
        stockQuantity: 800,
        listedDate: DateTime.now().subtract(const Duration(days: 4)),
      ),
      Product(
        id: '8',
        name: 'Wheat',
        description: 'High-quality wheat grains',
        category: 'Grains',
        farmerPrice: 30.0,
        marketPrice: 50.0,
        imageUrl: '🌾',
        farmerId: 'F1',
        farmerName: 'Ramesh Kumar',
        unit: 'kg',
        stockQuantity: 2000,
        listedDate: DateTime.now().subtract(const Duration(days: 7)),
      ),
    ];
  }

  static List<String> getCategories() {
    return ['All', 'Fruits', 'Vegetables', 'Grains', 'Other'];
  }
}
